# Vectorization

In [1]:
import numpy as np

a = np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [4]:
import time 
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorization version:" + str(1000*(toc-tic)) +"ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

249992.70533194876
Vectorization version:0.9992122650146484ms
249992.70533195185
For loop:381.0575008392334ms


# Broadcast Vecotization

In [5]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0,52.0,8.0],
             [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [7]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Python-Numpy Vectors

In [8]:
a = np.random.randn(5)

In [9]:
print(a)

[-0.7875531  -0.43759113 -1.46783904 -1.26032856 -0.37816489]


In [10]:
print(a.shape)

(5,)


In [11]:
print(a.T)

[-0.7875531  -0.43759113 -1.46783904 -1.26032856 -0.37816489]


In [12]:
print(np.dot(a,a.T))

4.697714082259163


In [13]:
a = np.random.randn(5,1)
print(a)

[[-2.98255779]
 [ 0.40491971]
 [-0.05233003]
 [-0.74597356]
 [-1.41680332]]


In [14]:
print(a.T)

[[-2.98255779  0.40491971 -0.05233003 -0.74597356 -1.41680332]]


In [15]:
print(np.dot(a,a.T))

[[ 8.89565094e+00 -1.20769642e+00  1.56077331e-01  2.22490924e+00
   4.22569776e+00]
 [-1.20769642e+00  1.63959969e-01 -2.11894594e-02 -3.02059393e-01
  -5.73691583e-01]
 [ 1.56077331e-01 -2.11894594e-02  2.73843178e-03  3.90368167e-02
   7.41413565e-02]
 [ 2.22490924e+00 -3.02059393e-01  3.90368167e-02  5.56476546e-01
   1.05689781e+00]
 [ 4.22569776e+00 -5.73691583e-01  7.41413565e-02  1.05689781e+00
   2.00733164e+00]]


In [16]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [17]:
print(c)

[[ 0.10901363 -0.04596953 -2.54252661]
 [-0.12040608 -3.6284862   0.39582316]
 [ 0.67217619  0.10774732  0.18176339]]
